/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function scan(input: string, options?: any | undefined | null): object
export declare function parse(input: any, options?: any | undefined | null): unknown
export declare function compileRe(state: any, options?: any | undefined | null, returnOutput?: boolean | undefined | null, returnState?: boolean | undefined | null): unknown
export declare function makeRe(input: string, options?: any | undefined | null, returnOutput?: boolean | undefined | null, returnState?: boolean | undefined | null): unknown
export declare function toRegex(source: string, options?: any | undefined | null): object
export declare function test(input: string, regex: unknown, options?: any | undefined | null): object
export declare function matchBase(input: string, glob: unknown, options?: any | undefined | null): boolean
export declare function isMatch(input: string, patterns: any, options?: any | undefined | null): boolean
export declare function compileMatcher(patterns: any, options?: any | undefined | null): NativeMatcher
export declare class NativeMatcher {
  test(input: string, returnObject?: boolean | undefined | null): unknown
  get state(): unknown
  get regex(): unknown
}
